name: Build and Run

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - name: Install paho-mqtt for python
      run : pip install paho-mqtt

    - name: Run Python Test Application
      run : cd Test && python inventoryAppTest.py

    - name: build Client 
      run: g++ Mqtt_C_Client\*.cpp -I include -L lib -l paho-mqtt3c -o Client

    - name: build ClientTestApplication
      run: g++ Test\*.cpp  --coverage -o ClientTest
   
    - name: move gcno to Test directory
      run: move *.gcno Test 
      
    - name: Run ClientTest App
      run: ./ClientTest.exe 

    - name: move .gcda files to Test directory
      run:  move *.gcda Test

    - name: ClientTest coverage report
      run:  gcov -r Test\*.cpp
