name: CT

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    - name: CT build
      run: msbuild D:\a\sync-devices-s1b6\sync-devices-s1b6\Client1\Client1.vcxproj /p:configuration=debug /p:platform=x64
    
    - name: CT run
      run: |
        .\Client1\x64\Debug\Client1.exe sub
      timeout-minutes:  3
