name: Limit complexity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck

    - name: Static Analysis on Mqtt_C_Client Folder files
      run: cppcheck Mqtt_C_Client/*.cpp

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3 -x"./Test/*" -x"./include/*" -x"./PythonInventoryApp/*"
